#!/bin/bash
SCRIPTS_ROOT="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPTS_ROOT/common/paths.sh"
source "$SCRIPTS_ROOT/.secrets"

# Auto-derive job name from the model env. Prefer a MODEL_ENV provided in the
# environment (e.g. by a sweep driver); otherwise read it from the launch script.
LAUNCH_SCRIPT="$1"
if [[ -z "$MODEL_ENV" ]]; then
    # Match both the plain form `MODEL_ENV=foo` and the overridable idiom
    # `: "${MODEL_ENV:=foo}"` (used by sweep-driven launch scripts).
    MODEL_ENV=$(grep -E '(^MODEL_ENV=|MODEL_ENV:=)' "$LAUNCH_SCRIPT" 2>/dev/null \
        | head -1 | sed -E 's/.*MODEL_ENV(:?=)//; s/["}]//g')
fi
if [[ -n "$MODEL_ENV" && -f "$SCRIPTS_ROOT/models/${MODEL_ENV}.env" ]]; then
    source "$SCRIPTS_ROOT/models/${MODEL_ENV}.env"
    JOB_NAME="$MODEL_NAME"
else
    JOB_NAME="${MODEL_ENV:-unknown}"
fi

DATE=$(date +%Y-%m-%d)
LOGDIR=$SLURM_LOG_DIR/$DATE
mkdir -p "$LOGDIR"

# Caller-injected sbatch options (e.g. --dependency=afterok:JOBID, used by
# dependency_submit.sh). These MUST precede the launch script on the sbatch
# command line: sbatch only parses options that come before the script path, so
# a flag passed as a trailing positional arg would be handed to the script
# instead. Word-split on whitespace (read -ra, no globbing). Empty by default
# => no change to a normal submission.
read -ra _extra_sbatch_args <<< "${EXTRA_SBATCH_ARGS:-}"

# Node exclusions live in a file so the list can be updated without editing this
# script. The path MUST be absolute: sbatch only treats --exclude as a filename
# when the argument starts with '/', otherwise it parses it as a node name.
# NOTE only ONE --exclude survives -- sbatch keeps the last and silently discards
# earlier ones, so a second flag (here or via EXTRA_SBATCH_ARGS) does not add to
# this list, it replaces it. To exclude more, add to the file or point at
# common/filter/exclude_all.txt (= exclude_slow_ep.txt + exclude_group23.txt).
# exclude_slow_ep.txt is regenerated by tools/ep_latency_report.py; hand-picked
# extras belong in common/filter/exclude_manual.txt, which that tool unions in.
EXCLUDE_FILE="$SCRIPTS_ROOT/common/filter/exclude_slow_ep.txt"

sbatch --job-name="$JOB_NAME" \
        --output=$LOGDIR/%x-%j.out \
        --error=$LOGDIR/%x-%j.err \
        --reservation=SD-69241-apertus-1-5-0 \
        --exclude="$EXCLUDE_FILE" \
        "${_extra_sbatch_args[@]}" \
        "$@"